### ISSUE TITLE
Light flickering and noticable performance loss

### ISSUE THREAD

**Issue by ConDawn** [ore-/AI_Graphics#106] opened 2020-05-17 15:18 UTC
There are issues with directional lights in hindsight of performance and flickering. Also the camera light causes massive performance loss. It's getting worse with characters involved.

## Expected Behavior

1# No flickering directional lights.
2# Better performance.

## Current Behavior

1# Watching an object from certain angles, causes directional lights to flicker.
2# A noticable performance loss with even slighter light settings. Especially the camera light seems to have a huge impact on that. After turned off, it's getting better. Yet adding a single directional light, the performance decreases noticably, especially when characters are involved, which wasn't the case beforehand.

## Used AI_Graphics Version

0.3.1

## Steps to Reproduce

1. Load default scene.
2. Add Character
3. Turn camera light on and off while rotating the camera to see the performance loss
5. Add directional light
6. Find the camera angles where the directional light begins to flicker.

**Comment by ore-** [comment] 2020-05-21 08:29
@ConDawn followed the exact steps, cannot reproduce performance issues (no loss of frames on my end) related to cam light, nor flickering related to directional light. feel free to include a link to a video.

**Comment by ore-** [comment] 2020-05-21 08:45
I'm closing this now, feel free to reopen if you have a reproducible case.

**Closed by ore-** 2020-05-21 08:45 UTC
