### ISSUE TITLE
Image Backgrounds Hide Character on Card

### ISSUE THREAD

**Issue by DEATHrocket777** [ore-/AI_Graphics#90] opened 2020-05-03 09:25 UTC
When I save a character card while using one of the image backgrounds (/userdata/bg) with AIG active, the character becomes hidden by the background in the card. This, for now, has forced me to return to using DHH.

## Expected Behavior
The character should show in the card with the background behind them.

## Current Behavior
The character is either disappearing, or is being hidden by the background image.

## Used AI_Graphics Version
AIGraphics v0.3.0

## Steps to Reproduce
EDITED
Type 1: Preset bug
1.Open character creator
2.Load either BB-AI2, Bubba's preset, or my preset
3.Change Background from "Flat Color" to "Image"
4.Save character
5.The card will be made, but the character will not appear on the card, only the background.

Type 2: Alt+Tab bug
1.Open character creator
2.Open AIG and load a preset that is known to work such as jjabrams or exaggerated
3.Change Background from "Flat Color" to "Image"
4.Alt+tab out of the game and back in
5.Save character

![AI_2020-05-03-02-14-45-189](https://user-images.githubusercontent.com/64728196/80910549-ff302980-8ce4-11ea-881a-4a035ccea01f.png)

UPDATE:
The problem only seems to happen with certain presets, such as mine, Bubba's, or the BB-AI2 preset. Other presets work fine, as long as you don't alt+tab the game. There's something in the settings causing the issue, and I've spent enough hours digging through settings and comparing screenshots (alt+tab'ing to look at screenshots is how I discovered that bug). Going back to DHH for now. Will fuss with this some more later.

**Comment by ore-** [comment] 2020-05-03 10:53
thanks for the report but I can't reproduce the problem, tried 9 permutations with/without img background from userdata/bg, with/without front frame, with/without rear frame. @hooh-hooah can you reproduce?

**Comment by Chernobog95** [comment] 2020-05-03 20:56
I think the issue is with screenshot manager, if you have alpha enabled, that may cause that. Wasn't issue before updating AIAPI and related stuff.

**Comment by DEATHrocket777** [comment] 2020-05-04 11:31
I tried this again with different presets loaded and have gotten closer to the root of the problem. When using the "exaggerated" and "jjabrams" presets, it works fine. When I use BB-AI2, Bubba's preset, or my preset, that's when the character disappears. I believe it must be something to do with the settings we've chosen.

**Comment by DEATHrocket777** [comment] 2020-05-04 12:14
I just asked Renatus to try saving a new character with my preset and he got the same problem, and again when he tried his own preset. There's definitely some setting that's messing up cards with image backgrounds. I'll try to recreate my preset starting with one of the presets that actually work and I'll see if anything I change causes this issue.

**Comment by DEATHrocket777** [comment] 2020-05-04 13:51
There seems to be an issue when using alt+tab that causes the problem. Once again, I had Renatus verify the problem on his end. 

Steps to Reproduce

1.Open character creator
2.Open AIG and load a preset that is known to work (jjabrams is what we used)
3.Change Background from "Flat Color" to "Image"
4.Alt+tab out of the game and back in
5.Save new character

**Comment by DEATHrocket777** [comment] 2020-05-04 14:14
Can also confirm it isn't a problem with alpha turned on in Screenshot Manager. I had the same issue with alpha turned off. It has to do with using alt+tab.

**Comment by DEATHrocket777** [comment] 2020-05-05 07:45
Here are two links to videos I have showcasing the bug in action.
https://twitter.com/DEATHrocket777/status/1257576284336435201?s=20
https://twitter.com/DEATHrocket777/status/1257576693490831360?s=20

**Comment by DEATHrocket777** [comment] 2020-05-05 07:50
@ore- I don't know if you get notified about comments on any posts, but just to let you know, I have gotten others to recreate this bug, and after further testing, have updated the instructions to reproduce.

**Comment by ore-** [comment] 2020-05-05 07:51
Thank you for the repro. @hooh-hooah and I will get to it when we can.

**Comment by DEATHrocket777** [comment] 2020-05-05 07:57
Good to know, thanks. I'll dig into the settings again later and let you know if I find anything.

**Comment by ore-** [comment] 2020-05-05 15:49
I can reproduce with the alt-tab method (any change of window focus triggers it) but I haven't been able to track down the source of the problem. Will keep looking.

**Comment by hooh-hooah** [comment] 2020-05-16 13:10
Well, There is something wrong with some graphics settings.
It's apparently appears in DHH and AIG. 

Don't expect this to be fixed in near time. This thing seems requires long time to investigate.

**Comment by ore-** [comment] 2020-05-21 13:40
hooh and I have decided that we won't spend any more time on this. one work around is to enable Forward Rendering before saving the character card. hooh also verified that with deferred rendering, DHH has the same issue. given the issue is related to core graphics api and there's a work around, we are closing this ticket.

**Closed by ore-** 2020-05-21 13:40 UTC
Labels: wontfix
