### ISSUE TITLE
SSR causing streaks and near clipping (See attachment)

### ISSUE THREAD

**Issue by MonkeyDocs** [ore-/AI_Graphics#53] opened 2020-04-12 07:08 UTC
## Used AI_Graphics Version
v0.2.0

![AAAA](https://user-images.githubusercontent.com/61049870/79062723-48392300-7ccf-11ea-84e1-3a458c0dc919.png)

## Steps to Reproduce
1. Use any kind of light with a reflective surface

**Comment by hooh-hooah** [comment] 2020-04-12 13:05
Can you post a scene as attachment?
You can replace the character to default tsubomi if you don't want to post character public.

**Comment by MonkeyDocs** [comment] 2020-04-12 13:53
Here
![scene](https://user-images.githubusercontent.com/61049870/79070366-f1037480-7d07-11ea-8b78-c4796268764e.png)

**Comment by ore-** [comment] 2020-05-02 06:56
I've spent sometime looking at ssr. I think the "streaks" may be caused by either the post processing stack v2 or a combination of it and the amplify shader. As pps v1 doesn't suffer from this. I've exposed the custom options for ssr in https://github.com/ore-/AI_Graphics/pull/83 but it doesn't solve the problem. Perhaps we need to look at a different ssr implementation. Closing this for now as it won't be fixed.

**Closed by ore-** 2020-05-02 06:56 UTC
Labels: bug
